#!/bin/bash

#ccache detection:
if [ -x /usr/bin/ccache ]; then
        CPP="/usr/bin/ccache g++"
else
        CPP="g++"
fi;

$CPP -std=c++0x -c -o obj/protocol_rpi.o src/protocol_rpi.cpp
$CPP -std=c++0x -c -o obj/ultrasonic_driver.o drivers/ultrasonic_driver.cpp
$CPP -std=c++0x -c -o obj/mt12232b_driver.o drivers/mt12232b_driver.cpp
$CPP -std=c++0x -c -o obj/util.o src/util.cpp
$CPP -std=c++0x -c -o obj/font.o drivers/font_8x8.c
$CPP -std=c++0x -c -o obj/main.o src/main.cpp

$CPP -std=c++0x -o susp obj/protocol_rpi.o obj/util.o obj/ultrasonic_driver.o obj/mt12232b_driver.o obj/font.o obj/main.o -l bcm2835
